import PyInstaller.__main__
import os
from pathlib import Path

# Get the current directory
current_dir = Path(__file__).parent.absolute()

# Create the resources directory if it doesn't exist
resources_dir = current_dir / "resources"
resources_dir.mkdir(exist_ok=True)

# Create a simple .ico file content if it doesn't exist
icon_path = resources_dir / "cyber_ninja.ico"
if not icon_path.exists():
    # You can replace this with your own icon file
    import base64
    icon_data = b"""
    AAABAAEAICAAAAEAIACoEAAAFgAAACgAAAAgAAAAQAAAAAEAIAAAAAAAABAAAMMOAADDDgAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZmZkFmZmZ
    BZmZmQWZmZkFmZmZBZmZmQWZmZkFmZmZBZmZmQWZmZkFmZmZBZmZmQWZmZkFmZmZBZmZmQWZmZkFmZmZBZmZmQWZmZkF
    mZmZBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmZmZBZmZmTyZmZk8mZmZPJmZmTyZmZk8mZmZPJmZmTyZ
    mZk8mZmZPJmZmTyZmZk8mZmZPJmZmTyZmZk8mZmZPJmZmTyZmZk8mZmZPJmZmTyZmZk8mZmZPJmZmTyZmZkFAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAACZmZkFmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ
    45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmQUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJmZmQWZmZnj
    mZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZ
    mZnjmZmZBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmZmZBZmZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZ
    meOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZkFAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAACZmZkFmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnj
    mZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmQUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJmZmQWZ
    mZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZ
    meOZmZnjmZmZBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmZmZBZmZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZ
    meOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZkFAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAACZmZkFmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZ
    mZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmQUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJmZ
    mQWZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ
    45mZmeOZmZnjmZmZBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmZmZBZmZmeOZmZnjmZmZ45mZmeOZmZnj
    mZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZkFAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZmZkFmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZ
    meOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmQUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ
    mZmQWZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZ
    mZ45mZmeOZmZnjmZmZBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmZmZBZmZmeOZmZnjmZmZ45mZmeOZmZnj
    mZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZkFAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZmZkFmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZ
    meOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmQUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ
    mZmQWZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZ
    mZ45mZmeOZmZnjmZmZBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmZmZBZmZmeOZmZnjmZmZ45mZmeOZmZnj
    mZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZkFAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZmZkFmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZ
    meOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmQUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ
    mZmQWZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZmZ45mZmeOZmZnjmZ
    mZ45mZmeOZmZnjmZmZBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmZmZBZmZmTyZmZk8mZmZPJmZmTyZmZk8
    mZmZPJmZmTyZmZk8mZmZPJmZmTyZmZk8mZmZPJmZmTyZmZk8mZmZPJmZmTyZmZk8mZmZPJmZmTyZmZkFAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZmZkFmZmZBZmZmQWZmZkFmZmZBZmZmQWZmZkFmZmZBZmZmQWZmZkFmZmZBZmZ
    mQWZmZkFmZmZBZmZmQWZmZkFmZmZBZmZmQWZmZkFmZmZBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    """
    with open(icon_path, 'wb') as f:
        f.write(base64.b64decode(icon_data))

# Define PyInstaller arguments
args = [
    'enhanced_gui_chatbot.py',  # Your main script
    '--onefile',  # Create a single executable
    '--windowed',  # Don't show console window
    '--icon', str(icon_path),  # Add icon
    '--name', 'CyberNinjaAI',  # Name of the executable
    '--add-data', f'audio{os.pathsep}audio',  # Include audio directory
    '--hidden-import', 'PIL._tkinter_finder',  # Required for customtkinter
    '--collect-all', 'customtkinter',  # Include all customtkinter files
]

# Add any additional files needed
for file in ['requirements.txt', '.env', 'example.settings.json']:
    if os.path.exists(file):
        args.extend(['--add-data', f'{file}{os.pathsep}{file}'])

print("Building executable...")
PyInstaller.__main__.run(args)
print("Build complete! Check the 'dist' folder for your executable.") 